<?php

/**
 * @file wsit.module
 * TODO: Enter file description here.
 */


function wsaio_permission() {
  return array(
    'whatserveramion' =>  array(
      'title' => t('See servername in title'),
      'restrict access' => TRUE,
      )
    );

}

/**
 * Implements hook_page_alter().
 */
function wsaio_page_alter(&$page) {

  // ensure user is logged in and that
  if (user_access('whatserveramion')) {
    drupal_set_title('[' . gethostname() . '] : ' . drupal_get_title());
  }


}
